import type { ExerciseLibraryItem } from '@/types'

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [

  // ── Chest ─────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Lower Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: '30-incline-plate-press',
    name: '30° Incline Plate Press',
    category: 'chest',
    equipment: 'other',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: '30-incline-dumbbell-press',
    name: '30° Incline Dumbbell Press',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-chest-fly',
    name: 'Cable Chest Fly',
    category: 'chest',
    equipment: 'cable',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    category: 'chest',
    equipment: 'machine',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: 'machine',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'plate-loaded-chest-press',
    name: 'Plate-Loaded Chest Press',
    category: 'chest',
    equipment: 'other',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'wide-grip-push-up',
    name: 'Wide-Grip Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'close-grip-push-up',
    name: 'Close-Grip Push-Up',
    category: 'arms',
    equipment: 'bodyweight',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'incline-push-up',
    name: 'Incline Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'decline-push-up',
    name: 'Decline Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'chest-dips',
    name: 'Chest Dips',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Chest'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'cable-crossover',
    name: 'Cable Crossover',
    category: 'chest',
    equipment: 'cable',
    primaryMuscles: ['Mid Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'low-to-high-cable-fly',
    name: 'Low-to-High Cable Fly',
    category: 'chest',
    equipment: 'cable',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'high-to-low-cable-fly',
    name: 'High-to-Low Cable Fly',
    category: 'chest',
    equipment: 'cable',
    primaryMuscles: ['Lower Chest'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Back (Rows) ───────────────────────────────────────────────────────────
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'pendlay-row',
    name: 'Pendlay Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'single-arm-dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'chest-supported-dumbbell-row',
    name: 'Chest-Supported Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'narrow-grip-cable-row',
    name: 'Narrow-Grip Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'wide-grip-cable-row',
    name: 'Wide-Grip Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Rear Delts'],
    tertiaryMuscles: ['Lats'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'neutral-grip-cable-row',
    name: 'Neutral-Grip Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'single-arm-cable-row',
    name: 'Single-Arm Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'plate-loaded-machine-row',
    name: 'Plate-Loaded Machine Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'wide-grip-plate-loaded-machine-row',
    name: 'Wide-Grip Plate-Loaded Machine Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Rear Delts'],
    tertiaryMuscles: ['Lats'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'close-grip-plate-loaded-machine-row',
    name: 'Close-Grip Plate-Loaded Machine Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'meadows-row',
    name: 'Meadows Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Upper Back'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },

  // ── Back (Vertical Pulls) ─────────────────────────────────────────────────
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'wide-grip-lat-pulldown',
    name: 'Wide-Grip Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'close-grip-lat-pulldown',
    name: 'Close-Grip Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'neutral-grip-lat-pulldown',
    name: 'Neutral-Grip Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'single-arm-lat-pulldown',
    name: 'Single-Arm Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'wide-grip-pull-up',
    name: 'Wide-Grip Pull-Up',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'arms',
    equipment: 'bodyweight',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Lats'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'neutral-grip-pull-up',
    name: 'Neutral-Grip Pull-Up',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    category: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-pullover',
    name: 'Cable Pullover',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Mid Chest'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Shoulders ─────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Side Delts'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: 'machine',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'landmine-press',
    name: 'Landmine Press',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Upper Chest'],
    tertiaryMuscles: ['Triceps'],
    movementPattern: 'vertical-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Rear Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'side-dumbbell-lateral-raise',
    name: 'Side Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Rear Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Rear Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'single-arm-cable-lateral-raise',
    name: 'Single-Arm Cable Lateral Raise',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    category: 'shoulders',
    equipment: 'machine',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Front Delts'],
    tertiaryMuscles: ['Rear Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'front-dumbbell-raise',
    name: 'Front Dumbbell Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Side Delts'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'front-plate-raise',
    name: 'Front Plate Raise',
    category: 'shoulders',
    equipment: 'other',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Side Delts'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-front-raise',
    name: 'Cable Front Raise',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Side Delts'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'plate-front-raise',
    name: 'Plate Front Raise',
    category: 'shoulders',
    equipment: 'other',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Side Delts'],
    tertiaryMuscles: ['Upper Chest'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'rear-delt-dumbbell-fly',
    name: 'Rear Delt Dumbbell Fly',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'rear-delt-cable-fly',
    name: 'Rear Delt Cable Fly',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    category: 'shoulders',
    equipment: 'machine',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Upper Back'],
    tertiaryMuscles: ['Side Delts'],
    movementPattern: 'horizontal-pull',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Traps'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-upright-row',
    name: 'Dumbbell Upright Row',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Side Delts'],
    secondaryMuscles: ['Traps'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'vertical-pull',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 9 },
  },

  // ── Arms (Biceps) ─────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'narrow-grip-barbell-curl',
    name: 'Narrow-Grip Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'wide-grip-barbell-curl',
    name: 'Wide-Grip Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    category: 'arms',
    equipment: 'ez-bar',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'close-grip-ez-bar-curl',
    name: 'Close-Grip EZ-Bar Curl',
    category: 'arms',
    equipment: 'ez-bar',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'wide-grip-ez-bar-curl',
    name: 'Wide-Grip EZ-Bar Curl',
    category: 'arms',
    equipment: 'ez-bar',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'alternating-dumbbell-curl',
    name: 'Alternating Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Brachialis'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cross-body-hammer-curl',
    name: 'Cross-Body Hammer Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Brachialis'],
    secondaryMuscles: ['Biceps'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'arms',
    equipment: 'machine',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-preacher-curl',
    name: 'Dumbbell Preacher Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'single-arm-cable-curl',
    name: 'Single-Arm Cable Curl',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'bayesian-cable-curl',
    name: 'Bayesian Cable Curl',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'spider-curl',
    name: 'Spider Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Brachioradialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'reverse-curl',
    name: 'Reverse Curl',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Brachioradialis'],
    secondaryMuscles: ['Brachialis'],
    tertiaryMuscles: ['Biceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Arms (Triceps) ────────────────────────────────────────────────────────
  {
    id: 'tricep-extension',
    name: 'Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-tricep-extension',
    name: 'Cable Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'rope-tricep-extension',
    name: 'Rope Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'straight-bar-tricep-extension',
    name: 'Straight-Bar Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'cable-overhead-tricep-extension',
    name: 'Cable Overhead Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-overhead-tricep-extension',
    name: 'Dumbbell Overhead Tricep Extension',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'single-arm-cable-tricep-extension',
    name: 'Single-Arm Cable Tricep Extension',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'single-arm-dumbbell-tricep-extension',
    name: 'Single-Arm Dumbbell Tricep Extension',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'ez-bar-skull-crusher',
    name: 'EZ-Bar Skull Crusher',
    category: 'arms',
    equipment: 'ez-bar',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-skull-crusher',
    name: 'Dumbbell Skull Crusher',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    category: 'arms',
    equipment: 'bodyweight',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Lower Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'bench-dips',
    name: 'Bench Dips',
    category: 'arms',
    equipment: 'bodyweight',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Mid Chest'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'horizontal-push',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'cable-kickback-tricep',
    name: 'Cable Kickback',
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'db-kickback',
    name: 'Dumbbell Kickback',
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Legs (Quads) ──────────────────────────────────────────────────────────
  {
    id: 'back-squat',
    name: 'Back Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'high-bar-squat',
    name: 'High-Bar Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'hack-squat-machine',
    name: 'Hack Squat Machine',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'narrow-stance-leg-press',
    name: 'Narrow-Stance Leg Press',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'forward-lunge',
    name: 'Forward Lunge',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Lunge',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'barbell-lunge',
    name: 'Barbell Lunge',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'reverse-step-up',
    name: 'Reverse Step-Up',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Quads'],
    tertiaryMuscles: ['Hamstrings'],
    movementPattern: 'lunge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'sissy-squat',
    name: 'Sissy Squat',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'squat',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'belt-squat',
    name: 'Belt Squat',
    category: 'legs',
    equipment: 'other',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'kettlebell-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    category: 'legs',
    equipment: 'kettlebell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'squat',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },

  // ── Legs (Hamstrings) ─────────────────────────────────────────────────────
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Lower Back', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'stiff-leg-deadlift',
    name: 'Stiff-Leg Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Lower Back', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Lower Back', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'single-leg-romanian-deadlift',
    name: 'Single-Leg Romanian Deadlift',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Core', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Lower Back', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 8 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'hamstring-curl',
    name: 'Hamstring Curl',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Calves'],
    tertiaryMuscles: ['Glutes'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'seated-hamstring-curl',
    name: 'Seated Hamstring Curl',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Calves'],
    tertiaryMuscles: ['Glutes'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'lying-hamstring-curl',
    name: 'Lying Hamstring Curl',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Calves'],
    tertiaryMuscles: ['Glutes'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'standing-hamstring-curl',
    name: 'Standing Hamstring Curl',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Calves'],
    tertiaryMuscles: ['Glutes'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'glute-ham-raise',
    name: 'Glute Ham Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Calves'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Legs (Glutes & Deadlifts) ─────────────────────────────────────────────
  {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings', 'Lower Back'],
    tertiaryMuscles: ['Quads', 'Lats'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Adductors', 'Hamstrings'],
    tertiaryMuscles: ['Quads', 'Lower Back'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 4, max: 10 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 8, max: 15 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'dumbbell-hip-thrust',
    name: 'Dumbbell Hip Thrust',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Adductors', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Core', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Core', 'Adductors'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'legs',
    equipment: 'cable',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Lower Back', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'legs',
    equipment: 'kettlebell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings', 'Lower Back'],
    tertiaryMuscles: ['Core', 'Forearms'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'kettlebell-romanian-deadlift',
    name: 'Kettlebell Romanian Deadlift',
    category: 'legs',
    equipment: 'kettlebell',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Lower Back', 'Core'],
    movementPattern: 'hinge',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'cable-kickback-glute',
    name: 'Cable Kickback',
    category: 'legs',
    equipment: 'cable',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Legs (Calves) ─────────────────────────────────────────────────────────
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'donkey-calf-raise',
    name: 'Donkey Calf Raise',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'smith-machine-calf-raise',
    name: 'Smith Machine Calf Raise',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'calf-press',
    name: 'Calf Press',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 7, max: 9 },
  },

  // ── Legs (Tibialis) ───────────────────────────────────────────────────────
  {
    id: 'tibialis-raise',
    name: 'Tibialis Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Tibialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'seated-tibialis-raise',
    name: 'Seated Tibialis Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Tibialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'standing-tibialis-raise',
    name: 'Standing Tibialis Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Tibialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'toe-raise',
    name: 'Toe Raise',
    category: 'legs',
    equipment: 'bodyweight',
    primaryMuscles: ['Tibialis'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },

  // ── Core ──────────────────────────────────────────────────────────────────
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'core',
    equipment: 'cable',
    primaryMuscles: ['Abs'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'weighted-crunch',
    name: 'Weighted Crunch',
    category: 'core',
    equipment: 'other',
    primaryMuscles: ['Abs'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'decline-sit-up',
    name: 'Decline Sit-Up',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'sit-up',
    name: 'Sit-Up',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors'],
    tertiaryMuscles: ['Forearms'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors'],
    tertiaryMuscles: ['Forearms'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'captains-chair-leg-raise',
    name: "Captain's Chair Leg Raise",
    category: 'core',
    equipment: 'machine',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs', 'Hip Flexors'],
    movementPattern: 'rotation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'v-up',
    name: 'V-Up',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip Flexors'],
    tertiaryMuscles: ['Quads'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'core',
    equipment: 'other',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Lats', 'Triceps'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Glutes'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs'],
    tertiaryMuscles: ['Glutes'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip Flexors'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Glutes', 'Lower Back'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    category: 'core',
    equipment: 'cable',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'rotation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'cable-woodchop',
    name: 'Cable Woodchop',
    category: 'core',
    equipment: 'cable',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs'],
    tertiaryMuscles: ['Front Delts'],
    movementPattern: 'rotation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs', 'Hip Flexors'],
    movementPattern: 'rotation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip Flexors'],
    tertiaryMuscles: ['Quads'],
    movementPattern: 'isolation',
    exerciseCategory: 'isolation',
    difficulty: 'beginner',
    recommendedRepRange: { min: 10, max: 20 },
    recommendedRpeRange: { min: 6, max: 8 },
  },

  // ── Full Body ─────────────────────────────────────────────────────────────
  {
    id: 'kettlebell-clean',
    name: 'Kettlebell Clean',
    category: 'full body',
    equipment: 'kettlebell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Front Delts'],
    tertiaryMuscles: ['Core', 'Forearms'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'kettlebell-snatch',
    name: 'Kettlebell Snatch',
    category: 'full body',
    equipment: 'kettlebell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Front Delts'],
    tertiaryMuscles: ['Core', 'Forearms'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'kettlebell-clean-and-press',
    name: 'Kettlebell Clean and Press',
    category: 'full body',
    equipment: 'kettlebell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Front Delts', 'Glutes', 'Triceps'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-thruster',
    name: 'Dumbbell Thruster',
    category: 'full body',
    equipment: 'dumbbell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Glutes', 'Front Delts', 'Triceps'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'barbell-thruster',
    name: 'Barbell Thruster',
    category: 'full body',
    equipment: 'barbell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Glutes', 'Front Delts', 'Triceps'],
    tertiaryMuscles: ['Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'full body',
    equipment: 'bodyweight',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Mid Chest', 'Quads', 'Front Delts'],
    tertiaryMuscles: ['Triceps', 'Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 3, max: 8 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'dumbbell-clean-and-press',
    name: 'Dumbbell Clean and Press',
    category: 'full body',
    equipment: 'dumbbell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Front Delts', 'Glutes', 'Triceps'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'full body',
    equipment: 'kettlebell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Front Delts', 'Abs', 'Glutes'],
    tertiaryMuscles: ['Quads', 'Hamstrings'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'advanced',
    recommendedRepRange: { min: 3, max: 6 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'farmers-walk',
    name: "Farmer's Walk",
    category: 'full body',
    equipment: 'other',
    primaryMuscles: ['Forearms'],
    secondaryMuscles: ['Traps', 'Abs'],
    tertiaryMuscles: ['Front Delts', 'Glutes'],
    movementPattern: 'carry',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    category: 'full body',
    equipment: 'other',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Forearms'],
    tertiaryMuscles: ['Traps', 'Glutes'],
    movementPattern: 'carry',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    category: 'full body',
    equipment: 'other',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Calves'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'sled-pull',
    name: 'Sled Pull',
    category: 'full body',
    equipment: 'other',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes', 'Quads'],
    tertiaryMuscles: ['Calves', 'Core'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    category: 'full body',
    equipment: 'other',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Abs', 'Triceps'],
    tertiaryMuscles: ['Upper Back'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    category: 'full body',
    equipment: 'bodyweight',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Calves'],
    tertiaryMuscles: ['Hamstrings', 'Core'],
    movementPattern: 'plyometric',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 3, max: 8 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'broad-jump',
    name: 'Broad Jump',
    category: 'full body',
    equipment: 'bodyweight',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Quads', 'Hamstrings'],
    tertiaryMuscles: ['Calves', 'Core'],
    movementPattern: 'plyometric',
    exerciseCategory: 'compound',
    difficulty: 'intermediate',
    recommendedRepRange: { min: 3, max: 8 },
    recommendedRpeRange: { min: 7, max: 9 },
  },
  {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'full body',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Front Delts', 'Quads'],
    tertiaryMuscles: ['Triceps', 'Glutes'],
    movementPattern: 'full-body',
    exerciseCategory: 'compound',
    difficulty: 'beginner',
    recommendedRepRange: { min: 6, max: 12 },
    recommendedRpeRange: { min: 6, max: 9 },
  },
]

/** EXERCISE_LIBRARY sorted A-Z by name — use this anywhere exercises are listed for browsing/searching. */
export const EXERCISE_LIBRARY_SORTED = [...EXERCISE_LIBRARY].sort((a, b) => a.name.localeCompare(b.name))

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  chest:       'Chest',
  back:        'Back',
  shoulders:   'Shoulders',
  arms:        'Arms',
  legs:        'Legs',
  core:        'Core',
  'full body': 'Full Body',
}
