import type { ExerciseLibraryItem } from '@/types'

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  // ── Chest ────────────────────────────────────────────────────────────────
  { id: 'bb-bench',          name: 'Barbell Bench Press',       category: 'chest',      equipment: 'barbell',    primaryMuscles: ['Pectorals', 'Triceps'] },
  { id: 'incline-bb-bench',  name: 'Incline Barbell Press',     category: 'chest',      equipment: 'barbell',    primaryMuscles: ['Upper Pectorals'] },
  { id: 'decline-bb-bench',  name: 'Decline Barbell Press',     category: 'chest',      equipment: 'barbell',    primaryMuscles: ['Lower Pectorals'] },
  { id: 'db-bench',          name: 'Dumbbell Bench Press',      category: 'chest',      equipment: 'dumbbell',   primaryMuscles: ['Pectorals', 'Triceps'] },
  { id: 'incline-db-bench',  name: 'Incline Dumbbell Press',    category: 'chest',      equipment: 'dumbbell',   primaryMuscles: ['Upper Pectorals'] },
  { id: 'db-fly',            name: 'Dumbbell Fly',              category: 'chest',      equipment: 'dumbbell',   primaryMuscles: ['Pectorals'] },
  { id: 'cable-fly',         name: 'Cable Fly',                 category: 'chest',      equipment: 'cable',      primaryMuscles: ['Pectorals'] },
  { id: 'machine-press',     name: 'Machine Chest Press',       category: 'chest',      equipment: 'machine',    primaryMuscles: ['Pectorals'] },
  { id: 'push-up',           name: 'Push-up',                   category: 'chest',      equipment: 'bodyweight', primaryMuscles: ['Pectorals', 'Triceps'] },
  { id: 'dip',               name: 'Dip',                       category: 'chest',      equipment: 'bodyweight', primaryMuscles: ['Pectorals', 'Triceps'] },
  // ── Back ─────────────────────────────────────────────────────────────────
  { id: 'bb-row',            name: 'Barbell Row',               category: 'back',       equipment: 'barbell',    primaryMuscles: ['Lats', 'Rhomboids'] },
  { id: 'pendlay-row',       name: 'Pendlay Row',               category: 'back',       equipment: 'barbell',    primaryMuscles: ['Lats', 'Rhomboids'] },
  { id: 'deadlift',          name: 'Deadlift',                  category: 'back',       equipment: 'barbell',    primaryMuscles: ['Erectors', 'Glutes', 'Hamstrings'] },
  { id: 'rdl',               name: 'Romanian Deadlift',         category: 'back',       equipment: 'barbell',    primaryMuscles: ['Hamstrings', 'Erectors'] },
  { id: 'sumo-dl',           name: 'Sumo Deadlift',             category: 'back',       equipment: 'barbell',    primaryMuscles: ['Glutes', 'Hamstrings'] },
  { id: 'trap-bar-dl',       name: 'Trap Bar Deadlift',         category: 'back',       equipment: 'barbell',    primaryMuscles: ['Quads', 'Glutes', 'Hamstrings'] },
  { id: 'pull-up',           name: 'Pull-up',                   category: 'back',       equipment: 'bodyweight', primaryMuscles: ['Lats', 'Biceps'] },
  { id: 'chin-up',           name: 'Chin-up',                   category: 'back',       equipment: 'bodyweight', primaryMuscles: ['Lats', 'Biceps'] },
  { id: 'lat-pulldown',      name: 'Lat Pulldown',              category: 'back',       equipment: 'cable',      primaryMuscles: ['Lats'] },
  { id: 'cable-row',         name: 'Seated Cable Row',          category: 'back',       equipment: 'cable',      primaryMuscles: ['Lats', 'Rhomboids'] },
  { id: 'db-row',            name: 'Single-Arm Dumbbell Row',   category: 'back',       equipment: 'dumbbell',   primaryMuscles: ['Lats', 'Rhomboids'] },
  { id: 't-bar-row',         name: 'T-Bar Row',                 category: 'back',       equipment: 'barbell',    primaryMuscles: ['Lats', 'Rhomboids'] },
  { id: 'face-pull',         name: 'Face Pull',                 category: 'back',       equipment: 'cable',      primaryMuscles: ['Rear Delts', 'Rhomboids'] },
  { id: 'good-morning',      name: 'Good Morning',              category: 'back',       equipment: 'barbell',    primaryMuscles: ['Hamstrings', 'Erectors'] },
  // ── Shoulders ────────────────────────────────────────────────────────────
  { id: 'ohp',               name: 'Overhead Press',            category: 'shoulders',  equipment: 'barbell',    primaryMuscles: ['Anterior Delts', 'Triceps'] },
  { id: 'push-press',        name: 'Push Press',                category: 'shoulders',  equipment: 'barbell',    primaryMuscles: ['Anterior Delts', 'Triceps'] },
  { id: 'db-press',          name: 'Seated Dumbbell Press',     category: 'shoulders',  equipment: 'dumbbell',   primaryMuscles: ['Delts'] },
  { id: 'arnold-press',      name: 'Arnold Press',              category: 'shoulders',  equipment: 'dumbbell',   primaryMuscles: ['Delts'] },
  { id: 'lateral-raise',     name: 'Lateral Raise',             category: 'shoulders',  equipment: 'dumbbell',   primaryMuscles: ['Lateral Delts'] },
  { id: 'front-raise',       name: 'Front Raise',               category: 'shoulders',  equipment: 'dumbbell',   primaryMuscles: ['Anterior Delts'] },
  { id: 'rear-delt-fly',     name: 'Rear Delt Fly',             category: 'shoulders',  equipment: 'dumbbell',   primaryMuscles: ['Rear Delts'] },
  { id: 'cable-lateral',     name: 'Cable Lateral Raise',       category: 'shoulders',  equipment: 'cable',      primaryMuscles: ['Lateral Delts'] },
  { id: 'upright-row',       name: 'Upright Row',               category: 'shoulders',  equipment: 'barbell',    primaryMuscles: ['Lateral Delts', 'Traps'] },
  { id: 'machine-lat-raise', name: 'Machine Lateral Raise',     category: 'shoulders',  equipment: 'machine',    primaryMuscles: ['Lateral Delts'] },
  // ── Biceps ───────────────────────────────────────────────────────────────
  { id: 'bb-curl',           name: 'Barbell Curl',              category: 'biceps',     equipment: 'barbell',    primaryMuscles: ['Biceps'] },
  { id: 'db-curl',           name: 'Dumbbell Curl',             category: 'biceps',     equipment: 'dumbbell',   primaryMuscles: ['Biceps'] },
  { id: 'hammer-curl',       name: 'Hammer Curl',               category: 'biceps',     equipment: 'dumbbell',   primaryMuscles: ['Brachialis', 'Biceps'] },
  { id: 'incline-db-curl',   name: 'Incline Dumbbell Curl',     category: 'biceps',     equipment: 'dumbbell',   primaryMuscles: ['Biceps'] },
  { id: 'cable-curl',        name: 'Cable Curl',                category: 'biceps',     equipment: 'cable',      primaryMuscles: ['Biceps'] },
  { id: 'ez-bar-curl',       name: 'EZ Bar Curl',               category: 'biceps',     equipment: 'ez-bar',     primaryMuscles: ['Biceps'] },
  { id: 'preacher-curl',     name: 'Preacher Curl',             category: 'biceps',     equipment: 'machine',    primaryMuscles: ['Biceps'] },
  { id: 'concentration-curl',name: 'Concentration Curl',        category: 'biceps',     equipment: 'dumbbell',   primaryMuscles: ['Biceps'] },
  // ── Triceps ───────────────────────────────────────────────────────────────
  { id: 'cgbp',              name: 'Close-Grip Bench Press',    category: 'triceps',    equipment: 'barbell',    primaryMuscles: ['Triceps'] },
  { id: 'skull-crusher',     name: 'Skull Crusher',             category: 'triceps',    equipment: 'ez-bar',     primaryMuscles: ['Triceps'] },
  { id: 'pushdown',          name: 'Tricep Pushdown',           category: 'triceps',    equipment: 'cable',      primaryMuscles: ['Triceps'] },
  { id: 'oh-tricep-ext',     name: 'Overhead Tricep Extension', category: 'triceps',    equipment: 'cable',      primaryMuscles: ['Triceps'] },
  { id: 'kickback',          name: 'Tricep Kickback',           category: 'triceps',    equipment: 'dumbbell',   primaryMuscles: ['Triceps'] },
  { id: 'diamond-push-up',   name: 'Diamond Push-up',           category: 'triceps',    equipment: 'bodyweight', primaryMuscles: ['Triceps'] },
  { id: 'machine-tricep',    name: 'Machine Tricep Extension',  category: 'triceps',    equipment: 'machine',    primaryMuscles: ['Triceps'] },
  // ── Quads ────────────────────────────────────────────────────────────────
  { id: 'back-squat',        name: 'Back Squat',                category: 'quads',      equipment: 'barbell',    primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'front-squat',       name: 'Front Squat',               category: 'quads',      equipment: 'barbell',    primaryMuscles: ['Quads'] },
  { id: 'goblet-squat',      name: 'Goblet Squat',              category: 'quads',      equipment: 'kettlebell', primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'leg-press',         name: 'Leg Press',                 category: 'quads',      equipment: 'machine',    primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'hack-squat',        name: 'Hack Squat',                category: 'quads',      equipment: 'machine',    primaryMuscles: ['Quads'] },
  { id: 'bulgarian-ss',      name: 'Bulgarian Split Squat',     category: 'quads',      equipment: 'dumbbell',   primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'lunge',             name: 'Lunge',                     category: 'quads',      equipment: 'dumbbell',   primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'leg-extension',     name: 'Leg Extension',             category: 'quads',      equipment: 'machine',    primaryMuscles: ['Quads'] },
  { id: 'step-up',           name: 'Step-Up',                   category: 'quads',      equipment: 'dumbbell',   primaryMuscles: ['Quads', 'Glutes'] },
  { id: 'sissy-squat',       name: 'Sissy Squat',               category: 'quads',      equipment: 'bodyweight', primaryMuscles: ['Quads'] },
  // ── Hamstrings ────────────────────────────────────────────────────────────
  { id: 'leg-curl',          name: 'Leg Curl',                  category: 'hamstrings', equipment: 'machine',    primaryMuscles: ['Hamstrings'] },
  { id: 'nordic-curl',       name: 'Nordic Hamstring Curl',     category: 'hamstrings', equipment: 'bodyweight', primaryMuscles: ['Hamstrings'] },
  { id: 'stiff-leg-dl',      name: 'Stiff-Leg Deadlift',        category: 'hamstrings', equipment: 'barbell',    primaryMuscles: ['Hamstrings', 'Erectors'] },
  { id: 'lying-leg-curl',    name: 'Lying Leg Curl',            category: 'hamstrings', equipment: 'machine',    primaryMuscles: ['Hamstrings'] },
  { id: 'db-rdl',            name: 'Dumbbell RDL',              category: 'hamstrings', equipment: 'dumbbell',   primaryMuscles: ['Hamstrings', 'Glutes'] },
  // ── Glutes ────────────────────────────────────────────────────────────────
  { id: 'hip-thrust',        name: 'Hip Thrust',                category: 'glutes',     equipment: 'barbell',    primaryMuscles: ['Glutes'] },
  { id: 'glute-bridge',      name: 'Glute Bridge',              category: 'glutes',     equipment: 'bodyweight', primaryMuscles: ['Glutes'] },
  { id: 'cable-kickback',    name: 'Cable Kickback',            category: 'glutes',     equipment: 'cable',      primaryMuscles: ['Glutes'] },
  { id: 'sumo-squat',        name: 'Sumo Squat',                category: 'glutes',     equipment: 'kettlebell', primaryMuscles: ['Glutes', 'Adductors'] },
  // ── Calves ────────────────────────────────────────────────────────────────
  { id: 'standing-calf',     name: 'Standing Calf Raise',       category: 'calves',     equipment: 'machine',    primaryMuscles: ['Gastrocnemius'] },
  { id: 'seated-calf',       name: 'Seated Calf Raise',         category: 'calves',     equipment: 'machine',    primaryMuscles: ['Soleus'] },
  { id: 'db-calf-raise',     name: 'Dumbbell Calf Raise',       category: 'calves',     equipment: 'dumbbell',   primaryMuscles: ['Gastrocnemius'] },
  // ── Core ─────────────────────────────────────────────────────────────────
  { id: 'plank',             name: 'Plank',                     category: 'core',       equipment: 'bodyweight', primaryMuscles: ['Transverse Abdominis', 'Core'] },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise',         category: 'core',       equipment: 'bodyweight', primaryMuscles: ['Hip Flexors', 'Rectus Abdominis'] },
  { id: 'ab-wheel',          name: 'Ab Wheel Rollout',          category: 'core',       equipment: 'other',      primaryMuscles: ['Core', 'Lats'] },
  { id: 'cable-crunch',      name: 'Cable Crunch',              category: 'core',       equipment: 'cable',      primaryMuscles: ['Rectus Abdominis'] },
  { id: 'russian-twist',     name: 'Russian Twist',             category: 'core',       equipment: 'bodyweight', primaryMuscles: ['Obliques'] },
  { id: 'pallof-press',      name: 'Pallof Press',              category: 'core',       equipment: 'cable',      primaryMuscles: ['Obliques', 'Core'] },
  { id: 'landmine-rotation', name: 'Landmine Rotation',         category: 'core',       equipment: 'barbell',    primaryMuscles: ['Obliques', 'Core'] },
  { id: 'sit-up',            name: 'Sit-up',                    category: 'core',       equipment: 'bodyweight', primaryMuscles: ['Rectus Abdominis'] },
  { id: 'v-up',              name: 'V-Up',                      category: 'core',       equipment: 'bodyweight', primaryMuscles: ['Core', 'Hip Flexors'] },
  // ── Olympic / Power ───────────────────────────────────────────────────────
  { id: 'power-clean',       name: 'Power Clean',               category: 'olympic',    equipment: 'barbell',    primaryMuscles: ['Full Body', 'Traps'] },
  { id: 'hang-clean',        name: 'Hang Clean',                category: 'olympic',    equipment: 'barbell',    primaryMuscles: ['Full Body', 'Traps'] },
  { id: 'power-snatch',      name: 'Power Snatch',              category: 'olympic',    equipment: 'barbell',    primaryMuscles: ['Full Body', 'Shoulders'] },
  { id: 'clean-jerk',        name: 'Clean & Jerk',              category: 'olympic',    equipment: 'barbell',    primaryMuscles: ['Full Body'] },
  { id: 'kb-swing',          name: 'Kettlebell Swing',          category: 'full body',  equipment: 'kettlebell', primaryMuscles: ['Glutes', 'Hamstrings', 'Core'] },
  { id: 'farmers-carry',     name: "Farmer's Carry",            category: 'full body',  equipment: 'dumbbell',   primaryMuscles: ['Core', 'Traps', 'Grip'] },
  { id: 'sled-push',         name: 'Sled Push',                 category: 'full body',  equipment: 'other',      primaryMuscles: ['Quads', 'Glutes', 'Core'] },
]

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  chest:       'Chest',
  back:        'Back',
  shoulders:   'Shoulders',
  biceps:      'Biceps',
  triceps:     'Triceps',
  quads:       'Quads',
  hamstrings:  'Hamstrings',
  glutes:      'Glutes',
  calves:      'Calves',
  core:        'Core',
  'full body': 'Full Body',
  olympic:     'Olympic',
}
